<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="29155" started-at="2018-09-26T22:23:03Z" finished-at="2018-09-26T22:23:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="29155" started-at="2018-09-26T22:23:03Z" finished-at="2018-09-26T22:23:32Z">
      <class name="com.qtpselenium.rediff.hybrid.testcases.portfoliosuite.LoginTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.qtpselenium.rediff.hybrid.testcases.portfoliosuite.LoginTest@26be92ad]" name="init" is-config="true" duration-ms="601" started-at="2018-09-26T18:23:03Z" finished-at="2018-09-26T18:23:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="initTest()[pri:0, instance:com.qtpselenium.rediff.hybrid.testcases.portfoliosuite.LoginTest@26be92ad]" name="initTest" is-config="true" duration-ms="162" started-at="2018-09-26T18:23:03Z" finished-at="2018-09-26T18:23:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method status="FAIL" signature="loginTest(java.util.Hashtable)[pri:0, instance:com.qtpselenium.rediff.hybrid.testcases.portfoliosuite.LoginTest@26be92ad]" name="loginTest" duration-ms="27294" started-at="2018-09-26T18:23:03Z" data-provider="getData" finished-at="2018-09-26T18:23:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=ashishthakur1983, ExpectedResult=Loginsuccess, Password=pass@1234, Runmode=Y, Browser=Edge}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.qtpselenium.rediff.hybrid.driver.DriverScript.executeKeywords(DriverScript.java:47)
	at com.qtpselenium.rediff.hybrid.testcases.portfoliosuite.LoginTest.loginTest(LoginTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: java.lang.AssertionError: The following asserts failed:
	Object Not Found username_id
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.qtpselenium.rediff.hybrid.keywords.GenericKeywords.reportFailure(GenericKeywords.java:424)
	at com.qtpselenium.rediff.hybrid.keywords.GenericKeywords.getObject(GenericKeywords.java:376)
	at com.qtpselenium.rediff.hybrid.keywords.AppKeywords.login(AppKeywords.java:34)
	... 31 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.qtpselenium.rediff.hybrid.testcases.portfoliosuite.LoginTest@26be92ad]" name="quit" is-config="true" duration-ms="1062" started-at="2018-09-26T18:23:31Z" finished-at="2018-09-26T18:23:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.qtpselenium.rediff.hybrid.testcases.portfoliosuite.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
